[theme]
primaryColor = "#1E88E5"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F5F5"
textColor = "#262730"
font = "Inter"

[server]
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[global]
developmentMode = false

[client]
toolbarMode = "minimal" 